In [1]:
from sklearn import linear_model
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

from sklearn import datasets, svm
from sklearn.feature_selection import SelectPercentile, f_classif

/usr/local/lib/python2.7/dist-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')

In [2]:
logistic = linear_model.LogisticRegression()

In [14]:
df_all=pd.read_csv('Data/Midsize SUV Regression data.csv', sep=',')
df_all.head()

,ID,Year,Make,MakeSeries,Segment,Demo_Census_4,Demo_Census_9,Cluster,YNV_GLB_16,Not Consider Other Makes,...,INT_Index,SS_Index,AEN_Index,Seats_Index,HVAC_Index,DD_Index,ENGTRN_Index,VDS_Index,FUEL_Index,APEAL_OSAT
0,226689BA,2016,Buick,Buick Enclave,Midsize SUV,NaN,NaN,0,1,0,...,0.805493,0.780964,0.754019,0.782178,0.759165,0.801894,0.784082,0.782532,0.600456,0.839768
1,23A7624B,2016,Dodge,Dodge Journey,Midsize SUV,NaN,NaN,3,2,0,...,0.805493,0.780964,0.754019,0.782178,0.759165,0.801894,0.784082,0.782532,0.600456,0.839768
2,23B2262Q,2016,Ford,Ford Explorer,Midsize SUV,NaN,NaN,3,0,0,...,0.805493,0.780964,0.754019,0.782178,0.759165,0.801894,0.784082,0.782532,0.600456,0.839768
3,2444269A,2016,Ford,Ford Explorer,Midsize SUV,NaN,NaN,2,1,0,...,0.805493,0.780964,0.754019,0.782178,0.759165,0.801894,0.784082,0.782532,0.600456,0.839768
4,23AA29BM,2016,Chevrolet,Chevrolet Traverse,Midsize SUV,NaN,NaN,4,1,0,...,0.805493,0.780964,0.754019,0.782178,0.759165,0.801894,0.784082,0.782532,0.600456,0.839768

In [15]:
X=df_all.values[:,9:]
y=df_all.values[:,8]
y = np.array(y).astype(int)
print(y[:10])
print(X[0,0])
df_all.head()

[1 2 0 1 1 1 1 1 1 1]
0

,ID,Year,Make,MakeSeries,Segment,Demo_Census_4,Demo_Census_9,Cluster,YNV_GLB_16,Not Consider Other Makes,...,INT_Index,SS_Index,AEN_Index,Seats_Index,HVAC_Index,DD_Index,ENGTRN_Index,VDS_Index,FUEL_Index,APEAL_OSAT
0,226689BA,2016,Buick,Buick Enclave,Midsize SUV,NaN,NaN,0,1,0,...,0.805493,0.780964,0.754019,0.782178,0.759165,0.801894,0.784082,0.782532,0.600456,0.839768
1,23A7624B,2016,Dodge,Dodge Journey,Midsize SUV,NaN,NaN,3,2,0,...,0.805493,0.780964,0.754019,0.782178,0.759165,0.801894,0.784082,0.782532,0.600456,0.839768
2,23B2262Q,2016,Ford,Ford Explorer,Midsize SUV,NaN,NaN,3,0,0,...,0.805493,0.780964,0.754019,0.782178,0.759165,0.801894,0.784082,0.782532,0.600456,0.839768
3,2444269A,2016,Ford,Ford Explorer,Midsize SUV,NaN,NaN,2,1,0,...,0.805493,0.780964,0.754019,0.782178,0.759165,0.801894,0.784082,0.782532,0.600456,0.839768
4,23AA29BM,2016,Chevrolet,Chevrolet Traverse,Midsize SUV,NaN,NaN,4,1,0,...,0.805493,0.780964,0.754019,0.782178,0.759165,0.801894,0.784082,0.782532,0.600456,0.839768

In [16]:
#feature selection
plt.figure(1)
plt.clf()
X_indices = np.arange(X.shape[-1])
selector = SelectPercentile(f_classif, percentile=10)
selector.fit(X, y)
scores = -np.log10(selector.pvalues_)
scores /= scores.max()
plt.bar(X_indices - .45, scores, width=.2,label=r'Univariate score ($-Log(p_{value})$)', color='g')
plt.xlabel('Feature number')
plt.legend(loc='upper right')
plt.show()

In [17]:
df_trunc=df_all.dropna()
df_trunc.head()

,ID,Year,Make,MakeSeries,Segment,Demo_Census_4,Demo_Census_9,Cluster,YNV_GLB_16,Not Consider Other Makes,...,INT_Index,SS_Index,AEN_Index,Seats_Index,HVAC_Index,DD_Index,ENGTRN_Index,VDS_Index,FUEL_Index,APEAL_OSAT
4925,B679B73G,2015,Chevrolet,Chevrolet Traverse,Midsize SUV,South,East South Central,4,2,0,...,0.333333,0.304597,0.333341,0.333348,0.333333,0.314998,0.290974,0.320056,0.111111,0.333333
4926,B743229G,2015,Jeep,Jeep Grand Cherokee,Midsize SUV,Midwest,East North Central,5,0,0,...,1.000000,0.974111,0.999948,0.999783,1.000000,1.000000,0.867453,0.961067,0.888889,1.000000
4927,B7485A4L,2015,Kia,Kia Sorento,Midsize SUV,Midwest,West North Central,4,0,0,...,0.825051,0.857035,0.896902,0.805433,0.757600,0.983823,1.000000,1.000000,0.666667,0.888889
4928,B7796B8Q,2015,Subaru,Subaru Outback,Midsize SUV,West,Pacific,1,1,0,...,0.986968,0.939445,0.932485,0.999783,0.964356,0.973388,0.937572,0.980533,0.888889,1.000000
4929,B77992BM,2015,Subaru,Subaru Outback,Midsize SUV,Northeast,Middle Atlantic,1,0,0,...,1.000000,0.999889,0.999948,0.999783,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [18]:
r4=df_trunc['Demo_Census_4'].values
region4=np.unique(r4).tolist()
print(region4)
r9=df_trunc['Demo_Census_9'].values
region9=np.unique(r9).tolist()

['Midwest', 'Northeast', 'South', 'West']

In [19]:
seriesList=df_all['MakeSeries'].unique()
print(seriesList)
#makeList=df_all['Make'].unique()
#print(makeList)

['Buick Enclave' 'Dodge Journey' 'Ford Explorer' 'Chevrolet Traverse'
 'GMC Acadia' 'Toyota Highlander' 'Subaru Outback' 'Honda Pilot'
 'Hyundai Santa Fe' 'Kia Sorento' 'Toyota 4Runner' 'Jeep Grand Cherokee'
 'Ford Edge' 'Nissan Pathfinder' 'Ford Flex' 'Nissan Murano'
 'Dodge Durango' 'Toyota Venza' 'Mazda CX-9' 'Honda Crosstour'
 'Subaru Tribeca']

In [21]:
frames=[]
keys=[]
X=df_all.values[:,9:]
y=df_all.values[:,8]
y = np.array(y).astype(int)
logistic.fit(X,y)
frames.append(pd.DataFrame(logistic.coef_))
keys.append('all')
for cluster in xrange(9):
    train_data = df_all.loc[df_all['Cluster']==cluster]
    X=train_data.values[:,9:]
    y=train_data.values[:,8]
    y = np.array(y).astype(int)
    logistic.fit(X,y)
    frames.append(pd.DataFrame(logistic.coef_))
    keys.append(cluster)
    
#for make in makeList:
#    train_data = df_all.loc[df_all['Make']==make]
#    X=train_data.values[:,7:]
#    y=train_data.values[:,6]
#    y = np.array(y).astype(int)
#    logistic.fit(X,y)
#    frames.append(pd.DataFrame(logistic.coef_))
#    keys.append(make)

for series in seriesList:
    train_data = df_all.loc[df_all['MakeSeries']==series]
    X=train_data.values[:,9:]
    y=train_data.values[:,8]
    y = np.array(y).astype(int)
    logistic.fit(X,y)
    frames.append(pd.DataFrame(logistic.coef_))
    keys.append(series)
    


for region in region4:
    train_data = df_trunc.loc[df_all['Demo_Census_4']==region]
    X=train_data.values[:,9:]
    y=train_data.values[:,8]
    y = np.array(y).astype(int)
    logistic.fit(X,y)
    frames.append(pd.DataFrame(logistic.coef_))
    keys.append(region)

for region in region9:
    train_data = df_trunc.loc[df_all['Demo_Census_9']==region]
    X=train_data.values[:,9:]
    y=train_data.values[:,8]
    y = np.array(y).astype(int)
    logistic.fit(X,y)
    frames.append(pd.DataFrame(logistic.coef_))
    keys.append(region)
    
result=pd.concat(frames,keys=keys).to_csv("results/Midsize SUV LogReg_coefs.csv")

In [ ]:
df_all[df_all.columns[28]].head()

In [ ]:
#region=['CHI','DET','IND','MIN','ALB','BOS','NYC','PHI','DAL','HOU','KCI','SAT','ATL','CHA','FLA','NAS','PIT','']